name: Question
description: Ask a question about SDK usage or behavior
labels: ["question"]
body:
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Before submitting a question, please ensure you have checked the following
      options:
        - label: I have read the [ttd-databricks SDK README](https://github.com/thetradedesk/ttd-databricks-python#readme)
          required: true
        - label: I have read the [TTD Data API Documentation](https://open.thetradedesk.com/advertiser/docsApp/GuidesAdvertiser/data/doc/DataApiReferenceAdvertiser)
          required: true
        - label: I have searched existing [issues](https://github.com/thetradedesk/ttd-databricks-python/issues)
          required: true

  - type: textarea
    id: question
    attributes:
      label: Question
      placeholder: Please provide a clear and concise description of the issue you are facing.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      placeholder: SDK version, endpoint, code snippet, or anything else that helps us understand your question.
    validations:
      required: false
