name: Import Marketplace listing notebooks

on:
  push:
    branches:
      - main
    paths:
      - 'listing/notebooks/*.ipynb'

jobs:
  import-notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@v0.282.0

      - name: Import notebooks
        run: databricks workspace import-dir --overwrite $SOURCE_PATH $TARGET_PATH
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_CLIENT_ID: ${{ vars.DATABRICKS_CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
          SOURCE_PATH: ./listing/notebooks
          TARGET_PATH: /Workspace/Users/${{ vars.DATABRICKS_CLIENT_ID }}/listing/notebooks/
